name: Build myfirstaddon package
on:
  push:
    branches:
      - main
jobs:
  build-addons:
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - run: git pull origin master --ff-only


      # Step for Windows 2019
      - name: Setup Node.js 
        if: matrix.os == 'windows-2019'
        uses: actions/setup-node@v3
        with:
          node-version: 10
  
      - name: Setup Node.js
        if: matrix.os == 'windows-2022'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build for Windows 2019
        if: matrix.os == 'windows-2019'
        shell: powershell
        run: |
          npm i -g node-gyp@8
          .\scripts\build-windows.ps1
  
      - name: Build for Windows 2022
        if: matrix.os == 'windows-2022'
        shell: powershell
        run: |
          npm i -g node-gyp@10
          .\scripts\build-windows-arm64.ps1


