name: Build myfirstaddon package

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
    steps:
      - uses: actions/checkout@v2

      - run: git pull origin master --ff-only

      - uses: actions/setup-node@v1
        with:
          node-version: 10

      # - name: Install Windows 2015 build tools
      #   if: matrix.os == 'windows-2019'
      #   run: npm i --global windows-build-tools --vs2015

      - name: Build for Windows
        if: matrix.os == 'windows-2019'
        shell: powershell
        run: |
          npm i -g node-gyp@8
          .\scripts\build-windows.ps1

      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            ./lib/bindings/linux/**/**/*.node
            ./lib/bindings/macos/**/*.node
            ./lib/bindings/windows/**/*.node
            ./lib/bindings/windows/**/*.dll
          retention-days: 1