name: Build myfirstaddon package
on:
  push:
    branches:
      - main
jobs:
  build-addons:
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: git pull origin main --ff-only
        name: Build for Windows 2019
        uses: actions/setup-node@v1
        with:
          node-version: 10
        shell: powershell
        run: |
          npm i -g node-gyp@8
          .\scripts\build-windows.ps1
