name: Build myfirstaddon package
on:
  push:
    branches:
      - main
jobs:
  build-windows-addons:
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
    steps:
      - run: echo "Hello, world!"
