name: Build myfirstaddon package
on:
  push:
    branches:
      - main
jobs:
  build-addons:
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: git pull origin master --ff-only
      - if: matrix.os == 'windows-2019'
        name: Build for Windows 2019
        run: echo "Hello, world! 2019"
      - if: matrix.os == 'windows-2022'
        name: Build for Windows 2022
        run: echo "Hello, world! 2022"
