name: Build myfirstaddon package
on:
  push:
    branches:
      - main
jobs:
  build-windows-addons:
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
    runs-on: ${{ matrix.os }}ß
    steps:
      - if: matrix.os == 'windows-2019'
        run: echo "Hello, world! 2019"
      - if: matrix.os == 'windows-2022'
        run: echo "Hello, world! 2022"
